name: cronet
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0
  ffigen: ^2.4.0

ffigen:
  name: CroNet
  description: Bindings to `cronet`.
  output: 'lib/cronet.dart'
  headers:
    entry-points:
      - 'cronet/include/cronet_c.h'
    include-directives: # include only these header files and necessary structs from other header files
      - '**cronet_c.h'
      - '**cronet.idl_c.h'